# Используем образ Python
FROM python:3.12-slim

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем все файлы проекта в контейнер
COPY . /app

# Устанавливаем зависимости
RUN pip install -r requirements.txt

# Открываем порт
EXPOSE 8080

# Запуск приложения с Gunicorn
CMD ["gunicorn", "-w", "4", "bot:app"]
